### ISSUE TITLE
separate sync (TCP) and gossip (UDP) ports

### ISSUE THREAD

**Issue by blenessy** [radixdlt/node-runner#10]
Two problems found by using the same port number (20000) for both TCP and UDP traffic:

1. Managed Kubernetes in Azure - external load balancer cannot handle this.
2. fritzbox 7490 cannot handle this

**Comment by CaptainSkywave** [comment]
> 
> 
> Two problems found by using the same port number (20000) for both TCP and UDP traffic:
> 
>     1. Managed Kubernetes in Azure - external load balancer cannot handle this.
> 
>     2. fritzbox 7490 cannot handle this

FYI - I have just had an update patch on my fritzbox 7490 - aaaand managed to open port 20000 as both TCP and UDP. 
So until further I shall wait to fully confirm if it holds up, once we run the test.
