### ISSUE TITLE
Allow user to continue with no further changes when running radixnode api account update-validator-config

### ISSUE THREAD

**Issue by RayOffiah** [radixdlt/node-runner#18]
This is just a suggestion, not an actual issue.

When the user is being asked for the parameters to change the validator config, it might be help speed things up a bit if we offer them an extra option when the question is presented. For example:

Do you want add/change the validator name and info url? ([Y]es, [N]o, E[x]ecute)

Yes - allow user to change setting
No - Skip to the next parameter
Execute - Run the command with the parameters filled in so far.

**Comment by shambupujar** [comment]
Makring this stale as this functionality has changed with core API from version 1.1.0
