### ISSUE TITLE
Systemd uses default /data as data location .

### ISSUE THREAD

**Issue by shambupujar** [radixdlt/node-runner#35]
Update the prompt for database location in systemd setup. Also  add option to ask whether user wants to start to the node or not as this would allow them to verify the files etc

**Comment by shambupujar** [comment]
https://github.com/radixdlt/node-runner/issues/35

**Comment by danisapfirov** [comment]
radixnode optimise-node creates folder /data
changing db.location in /etc/radixdlt/node/default.config
to db.location=/home/radixdlt/RADIXDB causes the node to stop
/data still remains fixed as default data location
